## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  
script:
  - xbuild Insya.NetDash.sln
  #- nunit-console Insya.NetDash.Tests/Insya.NetDash.Tests.csproj
