## Travis CI Integration

# Source language (using C since .NET and C# are not supported yet)
language: c

# Install dependencies needed to compile .NET and C#
install: sudo apt-get install mono-devel mono-gmcs

# Run the XBuild project file
script: xbuild Insya.NetDash/Insya.NetDash.csproj /p:Configuration=Release

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
